name: "Auto release on new downstream version of `expect`"
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set git user
        run: |
          git --no-pager log -1 --format='%an <%ae>'
          git config --global user.name "`git --no-pager log -1 --format='%an'`"
          git config --global user.email "`git --no-pager log -1 --format='%ae'`"
      - name: Set npm authToken
        run: npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - name: Install and save dependencies
        run: |
          npm install
          npm install --save-dev --save-exact expect@latest
          git status -bsuno
          git diff .
          git add package.json
          git commit -m "Update version"
      - name: Release package (if necessary)
        run: node auto-release.mjs `npm view expect version`
      - name: Push
        run: git push origin HEAD
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
